name: Release Chrome Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Run tests
      run: pnpm test

  build-and-release:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Build extension (if build script exists)
      run: |
        if pnpm run --if-present build --dry-run > /dev/null 2>&1; then
          pnpm run build
        else
          echo "No build script found, using source files directly"
        fi
      
    - name: Create extension package
      run: |
        # Create a clean directory for the extension
        mkdir -p dist
        
        # Copy extension files (excluding development files)
        cp manifest.json dist/
        cp *.js dist/ 2>/dev/null || true
        cp *.html dist/ 2>/dev/null || true
        cp *.css dist/ 2>/dev/null || true
        cp -r icons dist/ 2>/dev/null || true
        
        # Create zip file for Chrome Web Store
        cd dist
        zip -r ../tab-organizer-${{ github.ref_name }}.zip .
        cd ..
        
        echo "📦 Extension packaged as tab-organizer-${{ github.ref_name }}.zip"
        ls -la *.zip
      
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          tab-organizer-${{ github.ref_name }}.zip
        body: |
          ## Tab Organizer ${{ github.ref_name }}
          
          ### 📦 Installation
          Download the `tab-organizer-${{ github.ref_name }}.zip` file and load it as an unpacked extension in Chrome Developer Mode.
          
          ### 🧪 Testing
          All tests passed ✅
          
          ### 📋 Changes
          See commit history for detailed changes in this release.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}