name: Test Chrome Extension

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: ['latest']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest
        
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Run tests
      run: pnpm test
      
    - name: Run tests with coverage
      run: pnpm run test:coverage
      
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      if: matrix.node-version == 20
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: chrome-extension-coverage
        fail_ci_if_error: false

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Run linter
      run: pnpm run lint

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Validate extension structure
      run: |
        echo "📁 Chrome Extension Structure Check"
        echo "======================================"
        echo ""
        echo "📋 Required files:"
        [ -f "src/manifest.json" ] && echo "✅ src/manifest.json" || (echo "❌ src/manifest.json missing" && exit 1)
        
        echo ""
        echo "📋 Extension files:"
        [ -f "src/background.js" ] && echo "✅ src/background.js" || echo "ℹ️  src/background.js (not present)"
        [ -f "src/popup.html" ] && echo "✅ src/popup.html" || echo "ℹ️  src/popup.html (not present)"
        [ -f "src/popup.js" ] && echo "✅ src/popup.js" || echo "ℹ️  src/popup.js (not present)"
        [ -f "src/confirmation-dialog.html" ] && echo "✅ src/confirmation-dialog.html" || echo "ℹ️  src/confirmation-dialog.html (not present)"
        [ -f "src/confirmation-dialog.js" ] && echo "✅ src/confirmation-dialog.js" || echo "ℹ️  src/confirmation-dialog.js (not present)"
        [ -d "src/icons" ] && echo "✅ src/icons/ directory" || echo "ℹ️  src/icons/ directory (not present)"
        [ -d "src/utils" ] && echo "✅ src/utils/ directory" || echo "ℹ️  src/utils/ directory (not present)"
        
        echo ""
        echo "✅ Extension structure validation complete"
      
    - name: Validate manifest.json
      run: pnpm run validate