name: Test Chrome Extension

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: ['latest']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest
        
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Run tests
      run: pnpm test
      
    - name: Run tests with coverage
      run: pnpm run test:coverage
      
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      if: matrix.node-version == 20
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: chrome-extension-coverage
        fail_ci_if_error: false

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Run linter
      run: pnpm run lint

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Validate extension structure
      run: |
        echo "📁 Chrome Extension Structure Check"
        echo "======================================"
        echo ""
        echo "📋 Required files:"
        [ -f "manifest.json" ] && echo "✅ manifest.json" || (echo "❌ manifest.json missing" && exit 1)
        
        echo ""
        echo "📋 Extension files:"
        [ -f "background.js" ] && echo "✅ background.js" || echo "ℹ️  background.js (not present)"
        [ -f "popup.html" ] && echo "✅ popup.html" || echo "ℹ️  popup.html (not present)"
        [ -f "popup.js" ] && echo "✅ popup.js" || echo "ℹ️  popup.js (not present)"
        [ -f "confirmation-dialog.html" ] && echo "✅ confirmation-dialog.html" || echo "ℹ️  confirmation-dialog.html (not present)"
        [ -f "confirmation-dialog.js" ] && echo "✅ confirmation-dialog.js" || echo "ℹ️  confirmation-dialog.js (not present)"
        [ -d "icons" ] && echo "✅ icons/ directory" || echo "ℹ️  icons/ directory (not present)"
        
        echo ""
        echo "✅ Extension structure validation complete"
      
    - name: Validate manifest.json
      run: pnpm run validate